### PR TITLE
Fixed issue while create project name and base namespace

### PR DESCRIPTION
**Pull request by Amitpnk**
Hi @GregTrevellick ,

Issue has been fixed, below is screen shot of it,

image

### CODE REVIEW

**Review by GregTrevellick — APPROVED** [review]
Tested fine locally, will publish to marketplace shortly. Thanks very much

**Comment by GregTrevellick** [comment]
The synk issue was merely this - nothing to worry about.  
image
Detailed [here](https://support.snyk.io/hc/en-us/articles/360000910537-Manifest-not-found)

**Comment by ardalis** [comment]
How easy or difficult would it be for me to have this VS template automatically updated whenever I version the template in the repo (including publishing it to the VS marketplace)?

**Comment by GregTrevellick** [comment]
Hmm...let me have a think on that, will get back to you...

**Comment by GregTrevellick** [comment]
@ardalis 

Hi Steve - haven't automated publication to VS marketplace at this point - although have updated my fork from upstream & republished (v1.0.22). 

I have however set up an auto-merge from upstream when upstream is updated (via https://github.com/apps/pull) & will at some point simplify publication to VSMP (using .bat file or similar). If I can fully automate I will, but atm I foresee difficulty updating the VSMP version number - but we'll see.

In the mean time do tag me (github or twitter or email) whenever a new version needs publishing to VSMP as the app (https://github.com/apps/pull) doesn't notify me once it has updated my fork.

Cheers, Greg

**Pull request merged**
